version: "3.5"

services:
  api01: &api
    image: daandrn/php:rinha
    container_name: api01
    hostname: api01
    volumes:
    - ./ngphp.conf:/etc/nginx/nginx.conf:ro
    - ./index.php:/var/www/public/index.php
    - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      - DB_HOSTNAME=db
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "175MB"

  api02:
    <<: *api
    hostname: api02
    container_name: api02
    volumes:
    - ./ngphp.conf:/etc/nginx/nginx.conf:ro
    - ./index.php:/var/www/public/index.php
    - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      - DB_HOSTNAME=db
  
  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "50MB"

  db:
    image: postgres:16.1-alpine
    hostname: rinha
    container_name: db
    environment:
      - POSTGRES_PASSWORD=456
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "150MB"

networks:
  default:
    driver: bridge
    name: rinha
