version: "3.5"

services:
  api01: &api
    image: daandrn/php:latest
    hostname: api01
    volumes:
    - ./index.php:/var/www/public/index.php
    environment:
      - DB_HOSTNAME=db
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    volumes:
    - ./index.php:/var/www/public/index.php
    environment:
      - DB_HOSTNAME=db
      - PORT=8080
    ports:
      - "8081:8080"
  
  nginx:
    image: nginx:1.25.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  db:
    image: postgres:16.1-alpine
    hostname: rinha
    environment:
      - POSTGRES_PASSWORD=456
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
